server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=franchise
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: franchise
  jpa:
    properties:
      hibernate:
        default_schema: franchise
        jdbc:
          time_zone: UTC
    show-sql: true

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.courtcanva: debug

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
        allowed-headers: "*"
